version: '3.9'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "1StrongPwd!!"
      MSSQL_PID: "Developer"

    volumes:
      - mssql_data:/var/opt/mssql
      

volumes:
  mssql_data: